mode: dual
backend: ros2
auto_discover_glove_sn: true
auto_discover_hand_sn: true
hands:
  left:
    glove_sn: WG1JA02260412003
    hand_sn: 387D365B3533
    glove_device_name: glove_left
    retarget_config: wuji-retargeting/example/config/adaptive_analytical_wuji_glove_left.yaml
  right:
    glove_sn: WG1KA03260430006
    hand_sn: 3860364D3533
    glove_device_name: glove_right
    retarget_config: wuji-retargeting/example/config/adaptive_analytical_wuji_glove_right.yaml
