mode: dual

bringup_config: config/bringup_htc.yaml
hand_teleop_config: config/hand_teleop_wuji_glove.yaml
openvr_config: wuji-hand-teleop/src/input_devices/openvr_input/config/openvr_input.yaml
camera_config: config/camera_config.yaml
enable_camera: true

trigger:
  teleop:
    trigger_mode: keyboard
    keyboard_start: B
    keyboard_stop: E
  record:
    trigger_mode: keyboard
    keyboard_start: S
    keyboard_stop: D
